Repository nitrojs/nitro, pull requests merged in 2023-07, with the labels that each got.

#1364 fix(ui): primary color tokens; improve landing cards grid
  docs/content/0.index.md
  docs/tokens.config.ts
Labels: website

#1383 fix(types): enable `allowSyntheticDefaultImports` option by default
  src/build.ts
Labels: bug

#1388 feat: support regexps in external options
  src/rollup/plugins/externals-legacy.ts
  src/rollup/plugins/externals.ts
Labels: enhancement

#1386 docs(vercel): add note about top level `api/` directory
  docs/content/1.guide/3.routing.md
  docs/content/2.deploy/providers/vercel.md
Labels: documentation, ready

#1401 feat: support `exportConditions` and add worker default conditions
  src/options.ts
  src/presets/bun.ts
  src/presets/cloudflare-module.ts
  src/presets/cloudflare-pages.ts
  src/presets/cloudflare.ts
  src/presets/deno-deploy.ts
  src/presets/deno-server.ts
  src/presets/lagon.ts
  src/presets/netlify.ts
  src/presets/vercel.ts
  src/rollup/config.ts
  src/rollup/plugins/externals.ts
  src/types/nitro.ts
Labels: bug, enhancement, preset, ready

#1403 docs: add nitro plugins examples
  docs/content/1.guide/7.plugins.md
Labels: documentation, ready

#1409 docs: add custom preset instructions
  docs/content/2.deploy/3.custom-presets.md
Labels: documentation, preset, ready

#945 feat: allow ignoring public assets with `ignore` options
  src/build.ts
  test/fixture/nitro.config.ts
  test/fixture/public/_ignored.txt
  test/tests.ts
Labels: enhancement

#1436 feat: support `iis` server preset
  docs/content/2.deploy/providers/iis.md
  src/presets/iis-node.ts
  src/presets/iis.ts
  src/presets/index.ts
Labels: preset:iis

#1446 docs: fix typo
  src/runtime/app.ts
Labels: documentation, ready

#1442 docs: use `defineEventHandler` instead of `eventHandler`
  docs/content/1.guide/3.routing.md
  docs/content/1.guide/5.cache.md
  docs/content/2.deploy/providers/vercel.md
  docs/content/3.config.md
Labels: documentation

#1441 docs: remove auto-imported `defineNitroConfig`
  docs/content/1.guide/1.configuration.md
  docs/content/1.guide/3.routing.md
  docs/content/1.guide/4.storage.md
  docs/content/1.guide/5.cache.md
  docs/content/1.guide/6.assets.md
  docs/content/1.guide/7.plugins.md
  docs/content/2.deploy/0.index.md
  docs/content/2.deploy/3.custom-presets.md
  docs/content/2.deploy/providers/aws.md
  docs/content/2.deploy/providers/vercel.md
  docs/content/3.config.md
Labels: documentation, ready

#1440 chore(starter): add prepare command to starter
  package.json
Labels: enhancement, ready, starter

#1439 chore(starter): add `.npmrc`
  .npmrc
Labels: discussion

#1459 fix(static): safe decode path
  src/runtime/static.ts
Labels: bug

#1452 fix: split cookie headers
  package.json
  pnpm-lock.yaml
  src/runtime/app.ts
  src/runtime/entries/aws-lambda.ts
  src/runtime/entries/azure-functions.ts
  src/runtime/entries/azure.ts
  src/runtime/entries/bun.ts
  src/runtime/entries/cloudflare.ts
  src/runtime/entries/deno-deploy.ts
  src/runtime/entries/deno-server.ts
  src/runtime/entries/lagon.ts
  src/runtime/entries/netlify-edge.ts
  src/runtime/entries/netlify-lambda.ts
  src/runtime/entries/service-worker.ts
  src/runtime/entries/stormkit.ts
  src/runtime/entries/vercel-edge.ts
  src/runtime/utils.azure.ts
  src/runtime/utils.lambda.ts
  src/runtime/utils.ts
  test/fixture/api/headers.ts
  test/presets/aws-lambda.test.ts
  test/presets/netlify.test.ts
  test/tests.ts
Labels: enhancement, ready

#1438 fix(deno-deploy): treat all `https://` modules as external
  package.json
  pnpm-lock.yaml
  src/presets/deno-deploy.ts
Labels: preset:deno

#1465 chore: update references to `nuxt/nuxt`
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  scripts/bump-edge.ts
  scripts/release-edge.sh
Labels: chore

#1448 fix(prerender): skip redirects
  src/prerender.ts
Labels: enhancement, prerender

#1274 fix(aws-lambda,netlify): base64 encode binary responses
  src/runtime/entries/aws-lambda.ts
  src/runtime/entries/netlify-lambda.ts
  src/runtime/entries/stormkit.ts
  src/runtime/utils.lambda.ts
  test/fixture/routes/icon.png.ts
  test/tests.ts
Labels: enhancement, preset:netlify, preset:aws-lambda

#1502 chore: update github templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement, chore
