Repository nitrojs/nitro, pull requests merged in 2023-08, with the labels that each got.

#1518 fix: use relative paths in `tsconfig.json`
  src/build.ts
Labels: bug, types

#1451 docs: add about utils directory
  docs/content/1.guide/6.utils.md
Labels: documentation

#1456 docs(storage): add runtime storage configuration examples
  docs/content/1.guide/4.storage.md
Labels: documentation

#1531 feat(cloudflare-pages): improve cloudflare-pages adaptor to use dynamic imports
  src/presets/cloudflare-pages.ts
Labels: enhancement, pending, preset:cloudflare

#1530 fix(prerender): only match `href` attribute after whitespace
  src/prerender.ts
  test/fixture/routes/500.ts
  test/fixture/routes/prerender.ts
Labels: bug, prerender

#1528 feat: fully resolve type paths for auto-import declarations
  src/build.ts
Labels: enhancement

#1499 docs: prefer snake_case for preset names
  docs/content/2.deploy/0.index.md
  docs/content/2.deploy/providers/aws.md
  docs/content/2.deploy/providers/azure.md
  docs/content/2.deploy/providers/cloudflare.md
  docs/content/2.deploy/providers/deno.md
  docs/content/2.deploy/providers/github-pages.md
  docs/content/2.deploy/providers/iis.md
  docs/content/2.deploy/providers/netlify.md
  docs/content/2.deploy/providers/render.md
  docs/content/2.deploy/providers/vercel.md
Labels: documentation

#1307 docs(routing): add middleware section
  docs/content/1.guide/3.routing.md
Labels: documentation, ready

#1521 docs(plugins): add runtime hooks section
  docs/content/1.guide/7.plugins.md
Labels: documentation

#1497 fix(openapi): merge handlers with same route and different method
  src/runtime/routes/openapi.ts
  test/fixture/nitro.config.ts
Labels: bug

#1485 fix(prerender): exclude encoded `href` attributes from link extraction
  src/prerender.ts
  test/fixture/routes/prerender.ts
Labels: bug, prerender

#1184 feat(cache): support cached event handlers with varies
  docs/content/1.guide/5.cache.md
  src/runtime/cache.ts
Labels: enhancement, cache

#1474 feat(prerender): support for query links exploration
  src/prerender.ts
  src/types/nitro.ts
  test/fixture/routes/prerender.ts
  test/presets/cloudflare-pages.test.ts
  test/presets/vercel.test.ts
Labels: prerender

#527 feat: resolve actual subpaths before guessing
  src/rollup/plugins/externals.ts
Labels: enhancement, ready

#1561 chore(firebase): fix typos in warning message
  src/presets/firebase.ts
Labels: chore

#1572 fix: use relative paths in generated tsconfig
  src/build.ts
Labels: bug, types

#1584 fix: use relative type path to nitro #internal/nitro
  src/build.ts
Labels: bug

#1589 chore: lint test files as well
  package.json
  test/fixture/api/serialized/function.ts
  test/fixture/routes/file.ts
  test/presets/deno-server.test.ts
Labels: chore

#1591 fix(rollup): add `consola/core` alias
  src/rollup/config.ts
Labels: bug

#1603 fix(vercel,netlify): don't deprecate `swr` when `cache: false`
  src/presets/netlify.ts
  src/presets/vercel.ts
Labels: bug

#1547 docs(cloudflare): add environment variables instructions
  docs/content/2.deploy/providers/cloudflare.md
Labels: documentation, preset:cloudflare

#1549 test: add tests for environment variables and runtime config overrides
  test/presets/cloudflare-module.test.ts
  test/presets/cloudflare-pages.test.ts
  test/presets/cloudflare.test.ts
  test/presets/vercel-edge.test.ts
  test/tests.ts
Labels: test

#1377 feat(firebase): support renaming exported server function
  docs/content/2.deploy/providers/firebase.md
  src/presets/firebase.ts
  src/runtime/entries/firebase-gen-1.ts
  src/runtime/entries/firebase-gen-2.ts
  src/runtime/entries/firebase-gen-default.ts
  src/types/presets.ts
Labels: enhancement, preset:firebase

#1344 feat(azure): support custom configuration
  docs/content/2.deploy/providers/azure.md
  src/presets/azure.ts
  src/types/presets.ts
  test/presets/azure.test.ts
  test/tests.ts
Labels: enhancement, preset:azure

#1201 feat(node-server): support listening to unix sockets using `NITRO_UNIX_SOCKET`
  docs/content/2.deploy/1.node.md
  src/runtime/entries/node-server.ts
Labels: enhancement, good first issue

#1172 feat(cloudflare-module, cloudflare-pages): experimental dynamic imports
  docs/content/2.deploy/providers/cloudflare.md
  src/presets/cloudflare-module.ts
  src/presets/cloudflare-pages.ts
Labels: enhancement, preset:cloudflare

#1631 fix: correctly mark `middleware: false` for scanned routes
  src/scan.ts
Labels: bug

#1632 fix: pass relative ignore paths when scanning public assets
  src/build.ts
  test/fixture/nitro.config.ts
Labels: bug

#1640 fix: use new h3 generics for `defineCachedEventHandler`
  src/runtime/cache.ts
  test/fixture/types.ts
Labels: bug

#1647 fix: exclude typed body from `cachedEventHandler`
  src/runtime/cache.ts
  test/fixture/types.ts
Labels: bug

#1666 fix: resolve output dirs relative to `rootDir`
  src/options.ts
Labels: bug

#1676 fix(prerender): allow disabling html sub-folders
  src/options.ts
  src/prerender.ts
  src/types/nitro.ts
Labels: enhancement
