Repository nitrojs/nitro, pull requests merged in 2023-02, with the labels that each got.

#907 fix: provide fallback values for undefined runtime config
  src/options.ts
  src/utils/index.ts
Labels: bug

#908 fix(vercel): allow non-glob cache rules to apply to `/`
  src/presets/vercel.ts
Labels: bug

#906 fix: apply cached rules to overlaping wildcard patterns
  src/rollup/plugins/handlers.ts
  test/fixture/routes/rules/[...slug].ts
  test/presets/netlify.test.ts
  test/presets/node.test.ts
  test/presets/vercel.test.ts
  test/tests.ts
Labels: bug

#944 fix: correct `access-control-allow-methods` cors header name
  docs/content/3.config/index.md
  src/options.ts
  test/presets/netlify.test.ts
  test/presets/vercel.test.ts
  test/tests.ts
Labels: bug

#951 fix: don't render json response if url contains `/api/`
  src/runtime/utils.ts
Labels: bug

#959 chore(cli): mention `prepare` command in usage
  src/cli.ts
Labels: documentation

#958 docs(cloudflare): add info regarding `runtimeConfig` and environment variables
  docs/content/2.deploy/providers/cloudflare.md
Labels: documentation, preset:cloudflare

#964 feat: add lagon preset
  docs/content/2.deploy/providers/lagon.md
  src/presets/index.ts
  src/presets/lagon.ts
  src/runtime/entries/lagon.ts
Labels: enhancement, preset

#967 refactor(externals): sort `bundledDependencies` keys in output `package.json`
  src/rollup/plugins/externals-legacy.ts
  src/rollup/plugins/externals.ts
Labels: bug

#965 fix(cloudflare-pages): exclude assets from function call
  .gitignore
  src/presets/cloudflare.ts
  test/presets/cloudflare.test.ts
  test/tests.ts
Labels: enhancement

#968 fix(cloudflare-pages): handle assets only for get requests
  src/runtime/entries/cloudflare-pages.ts
Labels: bug

#969 fix: render json errors for CORS requests
  src/runtime/utils.ts
Labels: bug

#990 fix: only mock `debug` in production
  src/rollup/config.ts
Labels: bug

#981 fix: scan middleware and print tree list in ascending alphabetical order
  src/scan.ts
  src/utils/tree.ts
Labels: bug
