Repository nitrojs/nitro, pull requests merged in 2023-10, with the labels that each got.

#1534 feat(prerender): support `retry` and `retryDelay`
  docs/content/3.config.md
  src/options.ts
  src/prerender.ts
  src/types/nitro.ts
Labels: enhancement, prerender

#1756 feat: allow disabling compressed size calculation
  src/build.ts
  src/options.ts
  src/types/nitro.ts
  src/utils/tree.ts
Labels: enhancement

#1824 fix(prerender): decode html entities in rendered links
  src/prerender.ts
  test/fixture/routes/prerender.ts
Labels: bug

#1828 chore: use pnpm `shell-emulator` for windows local development
  .npmrc
Labels: windows

#1847 fix: recursively simplify returned objects
  src/types/serialize.ts
  test/fixture/types.ts
Labels: bug, types

#1859 fix(cloudflare-pages): filter out overlapping public assets dirs
  src/presets/cloudflare-pages.ts
Labels: bug

#1864 feat: support `inline` mode for `serveStatic`
  src/rollup/plugins/public-assets.ts
  src/runtime/virtual/public-assets.d.ts
  src/types/nitro.ts
Labels: enhancement
