Repository nitrojs/nitro, pull requests merged in 2024-06, with the labels that each got.

#2516 fix(public-assets): do not shadow paths that share prefix
  src/rollup/plugins/public-assets.ts
Labels: bug

#2517 fix(prerender): extract links from explicit html routes
  src/core/prerender/prerender.ts
  test/fixture/nitro.config.ts
  test/fixture/routes/prerender-custom.html.ts
  test/fixture/routes/prerender.ts
  test/presets/azure.test.ts
  test/presets/cloudflare-pages.test.ts
Labels: bug

#2529 chore: improve internal `tsconfig.json`
  package.json
  pnpm-lock.yaml
  scripts/gen-mirror.ts
  src/presets/netlify/legacy/runtime/netlify.ts
  tsconfig.json
Labels: chore

#2546 fix(core): scan handlers when initialising nitro
  src/core/nitro.ts
Labels: bug

#2561 fix(netlify): ensure preview command is correct
  src/presets/netlify/legacy/preset.ts
  src/presets/netlify/preset.ts
Labels: bug, preset:netlify

#2565 fix(handler-meta): check for `.name` with `undefined` value in `ObjectExpression`
  src/rollup/plugins/handlers-meta.ts
  test/fixture/api/meta/test.ts
Labels: v2
