Repository nitrojs/nitro, pull requests merged in 2024-03, with the labels that each got.

#2202 docs(providers): improve formatting & use new `undocs` components
  docs/2.deploy/20.providers/alwaysdata.md
  docs/2.deploy/20.providers/aws-amplify.md
  docs/2.deploy/20.providers/aws.md
  docs/2.deploy/20.providers/azure.md
  docs/2.deploy/20.providers/cleavr.md
  docs/2.deploy/20.providers/cloudflare.md
  docs/2.deploy/20.providers/deno-deploy.md
  docs/2.deploy/20.providers/digitalocean.md
  docs/2.deploy/20.providers/firebase.md
  docs/2.deploy/20.providers/flightcontrol.md
  docs/2.deploy/20.providers/github-pages.md
  docs/2.deploy/20.providers/heroku.md
  docs/2.deploy/20.providers/iis.md
  docs/2.deploy/20.providers/koyeb.md
  docs/2.deploy/20.providers/render.md
  docs/2.deploy/20.providers/stormkit.md
  docs/2.deploy/20.providers/vercel.md
Labels: documentation

#2239 fix(raw): use mime to chck binary types and exclude `.json`
  src/rollup/plugins/raw.ts
  test/fixture/assets/test.json
  test/fixture/routes/assets/all.ts
Labels: bug

#2250 fix: handle path negations when scanning public assets
  src/build.ts
  test/fixture/nitro.config.ts
  test/fixture/public/_unignored.txt
  test/presets/cloudflare-pages.test.ts
  test/tests.ts
Labels: bug

#2287 fix(prerender): call `nitroApp` close hook when done prerendering
  src/prerender.ts
  src/runtime/entries/nitro-prerenderer.ts
Labels: bug, prerender
